# Generated by Django 5.2 on 2025-04-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='имя')),
                ('description', models.TextField(verbose_name='описание')),
                ('image', models.ImageField(upload_to='fairy_tail/%y/%m/%d/')),
            ],
            options={
                'verbose_name': 'персонажи хвост феи',
                'verbose_name_plural': 'персонажи хвост феи',
            },
        ),
    ]
